# A message for commanding the state of the head lights
# Exposes all of the settings for the head lights that are visible in MIRA. Purpose not
# so clear.
# LEDStateX is a string of either "off" "on" or "fading"
# LEDPhaseX is frequency of fading?? in???
# LEDAmplitudeX is the brightness, 0...1.0
#
Header header
float32 HeadLightInterval 
string LEDState0 
float32 LEDPhase0
float32 LEDAmplitude0 
string LEDState1
float32 LEDPhase1
float32 LEDAmplitude1
string LEDState2
float32 LEDPhase2
float32 LEDAmplitude2
string LEDState3
float32 LEDPhase3
float32 LEDAmplitude3
string LEDState4
float32 LEDPhase4
float32 LEDAmplitude4 
string LEDState5 
float32 LEDPhase5
float32 LEDAmplitude5 
string LEDState6 
float32 LEDPhase6
float32 LEDAmplitude6
string LEDState7 
float32 LEDPhase7
float32 LEDAmplitude7