# A message for commanding the state of the head lights
# Exposes all of the settings for the head lights that are visible in MIRA. Purpose not
# so clear.
# LEDStateX is an integer {0: off, 1: on, 2: blinking, 3: fading}
# LEDPhaseX is an integer, is frequency of fading?? in??? ?????
# LEDAmplitudeX is the brightness, 0...1.0, maybe?
#
int16 HeadLightInterval 

int8 LEDState0 
int8 LEDPhase0
float32 LEDAmplitude0 

int8 LEDState1
int8 LEDPhase1
float32 LEDAmplitude1

int8 LEDState2
int8 LEDPhase2
float32 LEDAmplitude2

int8 LEDState3
int8 LEDPhase3
float32 LEDAmplitude3

int8 LEDState4
int8 LEDPhase4
float32 LEDAmplitude4 

int8 LEDState5 
int8 LEDPhase5
float32 LEDAmplitude5 

int8 LEDState6 
int8 LEDPhase6
float32 LEDAmplitude6

int8 LEDState7 
int8 LEDPhase7
float32 LEDAmplitude7